##### ============================= #####
#####        GENERAL SETTINGS      #####
##### ============================= #####

# Enable mouse support (pane resize, window select, scroll)
set -g mouse on

# Set default terminal type for proper 256-color support
set -g default-terminal "tmux-256color"

# Start window numbering from 1 instead of 0
set -g base-index 1


##### ============================= #####
#####        RELOAD CONFIG         #####
##### ============================= #####

# Press Prefix + R to reload tmux config
# Shows a confirmation message after reload
bind-key R source-file ~/.config/tmux/tmux.conf \; display-message "    Config Reloaded Successfully!"


##### ============================= #####
#####        PANE NAVIGATION       #####
##### ============================= #####

# Move between panes using vim-style keys
bind-key h select-pane -L   # Move left
bind-key j select-pane -D   # Move down
bind-key k select-pane -U   # Move up
bind-key l select-pane -R   # Move right

# Move between windows
bind-key C-h previous-window
bind-key C-l next-window

##### ============================= #####
#####        PANE SPLITTING        #####
##### ============================= #####

# Split panes quickly
bind-key H split-window -h  # Split horizontally (side-by-side)
bind-key V split-window -v  # Split vertically (top-bottom)


##### ============================= #####
#####        STATUS BAR POSITION   #####
##### ============================= #####

# Move status bar to the top
set-option -g status-position top


##### ============================= #####
#####        STATUS BAR STYLE      #####
##### ============================= #####

# Overall status bar colors
set -g status-style "bg=color234,fg=white"

# Inactive window style
set -g window-status-style "bg=default,fg=color240"

# Active window style (highlighted + bold)
set -g window-status-current-style "bg=default,fg=white,bold"

# Window formating
set -g window-status-format " #W"
set -g window-status-current-format " #W"

# Left side of status bar
# Default : [ Session Name ] 1:Window1 2:Window2
# Prevents the Session name from appearing on left side
set -g status-left ""

# Right side of status bar
# Shows current session name with green background
set -g status-right "#[fg=white,bg=green] #S #[default]"


##### ============================= #####
#####           PROMPT STYLE        #####
##### ============================= #####

# Message/command prompt styling
set -g message-style fg=white,bg=color234



##### ============================= #####
#####            PANE STYLE         #####
##### ============================= #####

# Active pane styling
set -g pane-active-border-style fg=color237

# Inactive pane styling
set -g pane-border-style fg=color237
